форма записи и меню-бургер работают
AnnaConda007/restaurantProject pull request #24
Opened 2023-04-05 12:23 UTC by AnnaConda007

2023-04-05 12:30 UTC, andrey-kudinov requested changes

2023-04-05 12:30 UTC, andrey-kudinov commented on src/js/modules/modal.js
> +      document.body.style.overflow = 'hidden'
Лучше использовать классы для таких вещей
Так как инлайн стили имеют больший вес и это потенциально это может привести к багам

2023-04-05 12:30 UTC, andrey-kudinov commented on src/js/modules/modal.js
> +const modal = (trigerSelector, modalSelector, modalClose, display) => {
Для 3 и более параметров считается лучше использовать объект как аргумент

2023-04-05 12:30 UTC, andrey-kudinov commented on src/js/modules/modal.js
> +  modalBtn.forEach((btn) => {
У тебя точно несколько триггеров для одной модалки?

2023-04-05 12:30 UTC, andrey-kudinov commented on src/js/modules/modal.js
> +  closeModal.addEventListener('click', () => {
И несколько кнопок закрытия?

2023-04-05 12:30 UTC, andrey-kudinov commented on src/js/main.js
> +import modal from "./modules/modal.js"
Так как у тебя достаточно приличная портянка импортов растёт, то советую использовать index.js внутри modules который аккумулирует импорты/экспорты

2023-04-06 13:42 UTC, AnnaConda007 commented on src/js/modules/modal.js
> +  modalBtn.forEach((btn) => {
item-order повторяется дважды, так как форма вызывается с 2 разных мест

2023-04-06 13:42 UTC, AnnaConda007 commented on src/js/modules/modal.js
> +  closeModal.addEventListener('click', () => {
*.modal используется при открытии формы открытой через всплывающее окно

2023-04-06 15:11 UTC, merged