формируется документ с заказом
AnnaConda007/restaurantProject pull request #27
Opened 2023-04-12 13:24 UTC by AnnaConda007

2023-04-12 15:41 UTC, andrey-kudinov requested changes

2023-04-12 15:41 UTC, andrey-kudinov commented on src/js/modules/shoppingCart.js
>      if (document.querySelector(".inner-container")) {
` if (!document.querySelector(".inner-container")) return`

... дальше код

2023-04-12 15:41 UTC, andrey-kudinov commented on src/js/modules/shoppingCart.js
> +            orderFormation()
`const fullHtmlDocument = orderFormation()`

2023-04-12 15:41 UTC, andrey-kudinov commented on src/js/modules/shoppingCart.js
> +          fullHtmlDocument = `
```
return `...`
```

2023-04-13 08:49 UTC, AnnaConda007 commented on src/js/modules/shoppingCart.js
> +        document.querySelector(".button--order").addEventListener("click", async() => {
новый код для отправки запроса ------

2023-04-14 13:11 UTC, merged